src/Models/Question.php
<?php

namespace Bigmom\Poll\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    use HasFactory;

    protected $casts = [
        'start_at' => 'datetime:Y-m-d H:i',
        'stop_at' => 'datetime:Y-m-d H:i',
    ];

    public const TYPE = [
        'Normal Poll',
    ];

    public function options()
    {
        return $this->hasMany(Option::class);
    }

    public function getTypeNameAttribute()
    {
        return SELF::TYPE[$this->type];
    }

    public function getStatusNameAttribute()
    {
        if ($this->is_not_started) {
            $statusName = 'Not started';
        } else if ($this->is_ended) {
            $statusName = 'Ended';
        } else {
            $statusName = 'Ongoing';
        }

        return $statusName;
    }

    public function getIsNotStartedAttribute()
    {
        return ($this->start_at === null || $this->start_at->isFuture());
    }

    public function getIsOngoingAttribute()
    {
        return (!$this->is_not_started && !$this->is_ended);
    }

    public function getIsEndedAttribute()
    {
        return ($this->stop_at && $this->stop_at->addMinutes(10)->isPast());
    }

    public function getInputTypeAttribute()
    {
        return ($this->min === 1 && $this->max === 1) ? 'radio' : 'checkbox';
    }
    
    public function getVoterCountAttribute()
    {
        return Vote::where('question_id', $this->id)->distinct('voter_id')->count();
    }

    public function getFormattedStartAtAttribute()
    {
        return $this->start_at ? $this->start_at->format('Y-m-d H:i:s') : null;
    }

    public function getFormattedStopAtAttribute()
    {
        return $this->stop_at ? $this->stop_at->format('Y-m-d H:i:s') : null;
    }

    public function deleteChildren()
    {
        foreach ($this->options as $option) {
            $option->deleteChildren()->delete();
        }

        return $this;
    }
}

src/resources/views/export/sheet/question.blade.php
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Type</th>
            <th>Is ballot</th>
            <th>Allow abstain</th>
            <th>Reveal result</th>
            <th>Min</th>
            <th>Max</th>
            <th>Group ID</th>
            <th>Start at</th>
            <th>Stop at</th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($questions as $question)
        <tr>
            <td>{{ $question->title }}</td>
            <td>{{ $question->type_name }}</td>
            <td>{{ $question->is_ballot ? "true" : "false" }}</td>
            <td>{{ $question->allow_abstain ? "true" : "false" }}</td>
            <td>{{ $question->allow_reveal_result ? "true" : "false" }}</td>
            <td>{{ $question->min }}</td>
            <td>{{ $question->max }}</td>
            <td>{{ $question->group_id }}</td>
            <td>{{ $question->start_at }}</td>
            <td>{{ $question->stop_at }}</td>
            @foreach ($question->options as $option)
            <td>{{ $option->text }} ({{ $option->cache_count }})</td>
            @endforeach
        </tr>
        @endforeach
    </tbody>
</table>
            